### PR TITLE
ad-network-id should be lowercase in the info.plist

### PR DESCRIPTION
**Pull request by egorlitvinenko**
https://developer.apple.com/forums/thread/663032

### CODE REVIEW

**Comment by dynamix** [comment]
Looks like this discussion is still ongoing. According to the latest test and comments from ngbinns the case needs to match between Info.plist, the SKAdnetwork signature and SKStoreProductParameterAdNetworkIdentifier.  

As Apple is still sending out ids that are uppercase and some might already be in use to generate signatures, I think it makes sense to wait with merging this until it is officially in the documentation and guaranteed to work.

**Comment by dynamix** [comment]
Looks like lowercase is preferred. What seems to be more important is that the casing is consistent for every step in the process to work (info.plist, SKAdNetwork signature, SKStoreProductParameterAdNetworkIdentifier).

**Comment by mbertschler** [comment]
It is now mentioned in the Apple documentation:
> **Important**
> You must lowercase the ad network identifier string.

https://developer.apple.com/documentation/storekit/skadnetwork/configuring_the_participating_apps

**Comment by dynamix** [comment]
I converted all ids to lowercase.

**Pull request closed without merging**
